// Dữ liệu mẫu các vị trí Marketing tại TP.HCM
// Bạn có thể thay/cập nhật bằng cách chỉnh sửa file này
const JOBS = [
    {
        id: 1,
        title: "Digital Marketing Executive",
        company: "Shopee Vietnam",
        district: "Quận 1",
        address: "Saigon Centre, Lê Lợi, Q.1",
        salary: { min: 15, max: 25 },
        level: "Junior",
        type: "Full-time",
        tags: ["SEO", "SEM", "Google Ads", "Facebook Ads"],
        posted: "2026-05-08",
        deadline: "2026-06-08",
        description: "Tham gia vận hành các chiến dịch Digital Marketing cho mảng E-commerce, tối ưu hiệu quả quảng cáo Google/Facebook và đo lường ROI.",
        requirements: [
            "1-2 năm kinh nghiệm Digital Marketing",
            "Thành thạo Google Ads, Facebook Ads Manager",
            "Có kiến thức về SEO, GA4, GTM",
            "Tiếng Anh giao tiếp tốt"
        ],
        benefits: ["Lương tháng 13", "Bảo hiểm sức khoẻ", "Laptop công ty", "Work from home 2 ngày/tuần"],
        applyUrl: "#"
    },
    {
        id: 2,
        title: "Content Marketing Specialist",
        company: "Tiki Corporation",
        district: "Quận 4",
        address: "Vạn Phúc City, Q.4",
        salary: { min: 18, max: 28 },
        level: "Middle",
        type: "Full-time",
        tags: ["Content", "Copywriting", "SEO", "Storytelling"],
        posted: "2026-05-09",
        deadline: "2026-06-15",
        description: "Xây dựng kế hoạch nội dung đa kênh, sản xuất content cho website, blog và social media của Tiki.",
        requirements: [
            "2+ năm kinh nghiệm Content/Copywriting",
            "Khả năng viết tiếng Việt mượt mà, sáng tạo",
            "Hiểu SEO content và keyword research",
            "Có portfolio bài viết đã xuất bản"
        ],
        benefits: ["Bonus theo KPI", "Bảo hiểm cao cấp", "13 ngày phép/năm", "Team building hàng quý"],
        applyUrl: "#"
    },
    {
        id: 3,
        title: "Marketing Manager",
        company: "VinGroup - VinFast",
        district: "Quận 7",
        address: "Phú Mỹ Hưng, Q.7",
        salary: { min: 40, max: 60 },
        level: "Manager",
        type: "Full-time",
        tags: ["Strategy", "Brand", "Leadership", "Automotive"],
        posted: "2026-05-07",
        deadline: "2026-06-30",
        description: "Quản lý team Marketing 8-10 người, xây dựng chiến lược thương hiệu và go-to-market cho dòng xe điện mới tại thị trường Đông Nam Á.",
        requirements: [
            "5+ năm kinh nghiệm Marketing, ít nhất 2 năm ở vị trí quản lý",
            "Có kinh nghiệm trong ngành automotive/FMCG/tech",
            "Tiếng Anh thành thạo (IELTS 7.0+)",
            "Tư duy chiến lược, kỹ năng lãnh đạo"
        ],
        benefits: ["Cổ phiếu ESOP", "Bảo hiểm gia đình", "Xe đưa đón", "Du lịch nước ngoài"],
        applyUrl: "#"
    },
    {
        id: 4,
        title: "Social Media Intern",
        company: "MoMo - M_Service",
        district: "Quận 3",
        address: "Tân Định, Q.3",
        salary: { min: 5, max: 7 },
        level: "Intern",
        type: "Part-time",
        tags: ["Social Media", "TikTok", "Instagram", "Trending"],
        posted: "2026-05-10",
        deadline: "2026-05-25",
        description: "Hỗ trợ team Social Media lên ý tưởng, sản xuất content cho Facebook, TikTok, Instagram của MoMo.",
        requirements: [
            "Sinh viên năm 3-4 khối ngành Marketing/Truyền thông",
            "Có khả năng làm việc 4 buổi/tuần",
            "Sáng tạo, bắt trend nhanh",
            "Biết Canva, CapCut là điểm cộng"
        ],
        benefits: ["Mentor 1-1", "Xét tuyển full-time sau thực tập", "Cơm trưa miễn phí"],
        applyUrl: "#"
    },
    {
        id: 5,
        title: "Performance Marketing Lead",
        company: "Lazada Vietnam",
        district: "Quận 1",
        address: "Saigon Tower, Q.1",
        salary: { min: 35, max: 50 },
        level: "Senior",
        type: "Hybrid",
        tags: ["Performance", "Google Ads", "Meta Ads", "Analytics"],
        posted: "2026-05-06",
        deadline: "2026-06-20",
        description: "Dẫn dắt các chiến dịch Performance Marketing với ngân sách hàng tháng 5+ tỷ VND, tối ưu CPA và ROAS.",
        requirements: [
            "4+ năm kinh nghiệm Performance Marketing",
            "Đã chạy ngân sách 1 tỷ+/tháng",
            "Thành thạo Looker Studio, GA4, Meta Pixel",
            "Tiếng Anh tốt - làm việc với team regional"
        ],
        benefits: ["Bonus theo quý", "Cổ phần Alibaba", "Hybrid 3-2", "Healthcare premium"],
        applyUrl: "#"
    },
    {
        id: 6,
        title: "SEO Specialist",
        company: "FPT Software",
        district: "Quận 9",
        address: "F-Town, Khu CNC Q.9 (TP. Thủ Đức)",
        salary: { min: 18, max: 30 },
        level: "Middle",
        type: "Full-time",
        tags: ["SEO", "Technical SEO", "Ahrefs", "Screaming Frog"],
        posted: "2026-05-05",
        deadline: "2026-06-10",
        description: "Phụ trách SEO cho 5+ website doanh nghiệp, audit kỹ thuật và xây dựng chiến lược backlink.",
        requirements: [
            "2+ năm kinh nghiệm SEO",
            "Thành thạo Ahrefs, SEMrush, Screaming Frog",
            "Có kiến thức HTML/CSS cơ bản",
            "Hiểu về Core Web Vitals, schema markup"
        ],
        benefits: ["Lương tháng 13-14", "Đào tạo certification miễn phí", "Cafeteria"],
        applyUrl: "#"
    },
    {
        id: 7,
        title: "Brand Marketing Executive",
        company: "Unilever Vietnam",
        district: "Quận 1",
        address: "Bitexco Tower, Q.1",
        salary: { min: 22, max: 32 },
        level: "Junior",
        type: "Full-time",
        tags: ["Brand", "FMCG", "Campaign", "Research"],
        posted: "2026-05-08",
        deadline: "2026-06-08",
        description: "Hỗ trợ Brand Manager triển khai chiến dịch 360 cho các nhãn hàng chăm sóc cá nhân.",
        requirements: [
            "1-3 năm kinh nghiệm Brand/Marketing FMCG",
            "Tốt nghiệp ĐH ngành Marketing/Kinh tế",
            "Tiếng Anh giỏi (IELTS 6.5+)",
            "Tư duy phân tích thị trường"
        ],
        benefits: ["Lương 13.5 tháng", "Bonus performance", "Bảo hiểm gia đình", "Sản phẩm miễn phí"],
        applyUrl: "#"
    },
    {
        id: 8,
        title: "Email Marketing Specialist",
        company: "Be Group",
        district: "Quận Bình Thạnh",
        address: "Vinhomes Central Park, Bình Thạnh",
        salary: { min: 14, max: 20 },
        level: "Junior",
        type: "Remote",
        tags: ["Email", "CRM", "Mailchimp", "Automation"],
        posted: "2026-05-09",
        deadline: "2026-06-09",
        description: "Thiết kế, triển khai và đo lường các chiến dịch email marketing/CRM cho người dùng Be.",
        requirements: [
            "1-2 năm kinh nghiệm Email/CRM Marketing",
            "Sử dụng được Mailchimp, ActiveCampaign hoặc tương đương",
            "Biết HTML email cơ bản",
            "Có tư duy A/B testing"
        ],
        benefits: ["Remote 100%", "Macbook làm việc", "Voucher Be hàng tháng"],
        applyUrl: "#"
    },
    {
        id: 9,
        title: "Marketing Communications Manager",
        company: "Techcombank",
        district: "Quận 1",
        address: "Mê Linh Point Tower, Q.1",
        salary: { min: 35, max: 55 },
        level: "Manager",
        type: "Full-time",
        tags: ["MarCom", "PR", "Banking", "Strategy"],
        posted: "2026-05-04",
        deadline: "2026-06-15",
        description: "Quản lý hoạt động truyền thông tích hợp, PR và quan hệ truyền thông cho các sản phẩm ngân hàng số.",
        requirements: [
            "5+ năm kinh nghiệm MarCom/PR",
            "Ưu tiên có kinh nghiệm trong ngành Banking/Fintech",
            "Quan hệ tốt với báo chí",
            "Tiếng Anh thành thạo"
        ],
        benefits: ["Lương 16 tháng", "Vay ưu đãi nhân viên", "Healthcare cao cấp", "Du lịch nước ngoài"],
        applyUrl: "#"
    },
    {
        id: 10,
        title: "Growth Marketing Analyst",
        company: "VNG Corporation",
        district: "Quận 7",
        address: "VNG Campus, Tân Thuận Q.7",
        salary: { min: 20, max: 30 },
        level: "Middle",
        type: "Hybrid",
        tags: ["Growth", "Data", "SQL", "A/B Testing"],
        posted: "2026-05-07",
        deadline: "2026-06-12",
        description: "Phân tích hành vi user, xây dựng growth experiment và funnel cho các sản phẩm Zalo/ZaloPay.",
        requirements: [
            "2+ năm kinh nghiệm Growth/Data Marketing",
            "Thành thạo SQL, Mixpanel/Amplitude",
            "Có tư duy thí nghiệm A/B",
            "Tiếng Anh đọc hiểu tốt"
        ],
        benefits: ["Bonus quý", "ESOP", "Free meals", "Gym in office"],
        applyUrl: "#"
    },
    {
        id: 11,
        title: "Influencer Marketing Executive",
        company: "Hasaki.vn",
        district: "Quận 10",
        address: "3/2 Q.10",
        salary: { min: 12, max: 18 },
        level: "Junior",
        type: "Full-time",
        tags: ["Influencer", "KOL", "TikTok", "Beauty"],
        posted: "2026-05-10",
        deadline: "2026-06-01",
        description: "Quản lý quan hệ với KOL/KOC, triển khai các chiến dịch booking influencer cho mỹ phẩm.",
        requirements: [
            "1+ năm kinh nghiệm KOL/Influencer",
            "Có database KOL/KOC mảng beauty là lợi thế",
            "Đàm phán giá tốt",
            "Theo dõi xu hướng TikTok hàng ngày"
        ],
        benefits: ["Sản phẩm mỹ phẩm miễn phí", "Bonus campaign", "Du lịch hàng năm"],
        applyUrl: "#"
    },
    {
        id: 12,
        title: "Marketing Director",
        company: "The CrownX (Masan)",
        district: "Quận 1",
        address: "Mplaza Saigon, Q.1",
        salary: { min: 80, max: 120 },
        level: "Manager",
        type: "Full-time",
        tags: ["Director", "Retail", "Strategy", "Leadership"],
        posted: "2026-05-03",
        deadline: "2026-07-01",
        description: "Lãnh đạo bộ phận Marketing 50+ người, định hướng chiến lược thương hiệu cho hệ sinh thái retail.",
        requirements: [
            "10+ năm kinh nghiệm Marketing, 5+ năm cấp Director",
            "Đã quản lý ngân sách 100+ tỷ/năm",
            "Background MBA là lợi thế",
            "Tiếng Anh thành thạo"
        ],
        benefits: ["Lương + bonus + ESOP rất cạnh tranh", "Xe + tài xế", "Nhà ở công ty"],
        applyUrl: "#"
    },
    {
        id: 13,
        title: "TikTok Content Creator",
        company: "Coolmate",
        district: "Quận Bình Thạnh",
        address: "Phan Văn Trị, Bình Thạnh",
        salary: { min: 10, max: 16 },
        level: "Junior",
        type: "Full-time",
        tags: ["TikTok", "Video", "Content", "Fashion"],
        posted: "2026-05-09",
        deadline: "2026-05-30",
        description: "Lên ý tưởng và sản xuất video TikTok hàng ngày cho thương hiệu thời trang nam Coolmate.",
        requirements: [
            "Có kênh TikTok cá nhân 5k+ followers là điểm cộng",
            "Biết quay/dựng video bằng CapCut",
            "Sáng tạo, bắt trend nhanh",
            "Tự tin xuất hiện trên camera"
        ],
        benefits: ["Voucher quần áo Coolmate", "Studio quay tại văn phòng", "Bonus theo lượt view"],
        applyUrl: "#"
    },
    {
        id: 14,
        title: "Product Marketing Manager",
        company: "Grab Vietnam",
        district: "Quận 1",
        address: "Vincom Center, Q.1",
        salary: { min: 50, max: 75 },
        level: "Senior",
        type: "Hybrid",
        tags: ["Product Marketing", "GTM", "Tech", "B2B"],
        posted: "2026-05-06",
        deadline: "2026-06-25",
        description: "Phụ trách go-to-market cho các tính năng mới của ứng dụng Grab tại thị trường Việt Nam.",
        requirements: [
            "5+ năm Product Marketing tại công ty công nghệ",
            "Hiểu rõ user research, segmentation, positioning",
            "Tiếng Anh thành thạo (làm việc với team Singapore)",
            "Tư duy data-driven"
        ],
        benefits: ["Stock options", "Healthcare gia đình", "GrabFood credit hàng tháng"],
        applyUrl: "#"
    },
    {
        id: 15,
        title: "Affiliate Marketing Executive",
        company: "Sendo",
        district: "Quận Phú Nhuận",
        address: "Phan Đình Phùng, Phú Nhuận",
        salary: { min: 13, max: 19 },
        level: "Junior",
        type: "Full-time",
        tags: ["Affiliate", "Partnership", "Performance"],
        posted: "2026-05-08",
        deadline: "2026-06-08",
        description: "Phát triển và quản lý hệ thống affiliate, tìm kiếm publisher mới và tối ưu hoa hồng.",
        requirements: [
            "1-2 năm kinh nghiệm Affiliate/Partnership Marketing",
            "Có network publisher là lợi thế",
            "Thành thạo Excel, làm việc với data",
            "Kỹ năng đàm phán tốt"
        ],
        benefits: ["Bonus theo doanh thu", "Lương tháng 13", "Healthcare"],
        applyUrl: "#"
    },
    {
        id: 16,
        title: "Marketing Intern - Event",
        company: "Vietcetera Media",
        district: "Quận 2",
        address: "Thảo Điền, Q.2 (TP. Thủ Đức)",
        salary: { min: 4, max: 6 },
        level: "Intern",
        type: "Full-time",
        tags: ["Event", "Marketing", "Production"],
        posted: "2026-05-10",
        deadline: "2026-05-20",
        description: "Hỗ trợ tổ chức các sự kiện kết nối thương hiệu - cộng đồng cho Vietcetera.",
        requirements: [
            "Sinh viên năm 3-4 khối ngành liên quan",
            "Có thể làm full-time 6 tháng",
            "Năng động, không ngại di chuyển",
            "Tiếng Anh giao tiếp"
        ],
        benefits: ["Trợ cấp sự kiện", "Mentor từ founder", "Networking với KOLs"],
        applyUrl: "#"
    },
    {
        "id": 17,
        "title": "Nhân Viên Truyền Thông Kỹ Thuật Số / Digital Associate",
        "company": "Trang Văn hóa công ty",
        "district": "P. Xuân Hoà",
        "address": "An Phú Plaza, Tầng 7, 117-119 Lý Chính Thắng, P. Xuân Hoà, TP. HCM",
        "salary": "Thương lượng",
        "level": "Nhân viên",
        "type": "Full-time",
        "tags": [
            "Truyền Thông",
            "Quảng Cáo Truyền Thông",
            "Truyền Thông Thương Hiệu",
            "Digital Marketing",
            "SEO Content Creation"
        ],
        "posted": "15/04/2026",
        "deadline": "Hết hạn trong 13 ngày",
        "description": "•\tXây dựng nội dung đa nền tảng ngành dược (social media), Đóng góp ý tưởng, cùng team triển khai các chiến dịch “content marketing” theo mục tiêu tiếp thị tổng thể.\n•\tHiểu các nhóm điều trị, chức năng sản phẩm của công ty để xây dựng nội dung theo mô hình AIDA hướng tới chuyển đổi.\n•\tĐề xuất sáng tạo nội dung hữu ích, Lên kịch bản, chỉnh sửa, xây dựng video, hình ảnh, phù hợp với các nền tảng.\n•\tHỗ trợ sự kiện, thiết kế và chỉnh sửa các nội dung xoay quanh hành trình sự kiện như thư mời (hình ảnh, video), thiết kế bộ câu hỏi cho game theo sự kiện, gửi thông báo ZNS/ SMS/ khảo sát và phân loại để “remarketing” sau khi có dữ liệu.\n•\tDevelop multichannel content of the pharmaceutical industry (social media), contribute ideas, and collaborate with the team to execute content marketing campaigns aligned with overall marketing goals.\n•\tUnderstand treatment groups and product functions of the company to create content following the AIDA model aimed at conversion.\n•\tPropose creative and useful content, script writing, editing, creating videos, images, suitable for various platforms.\n•\tSupport events, design and edit content related to event journeys such as invitations (images, videos), design question sets for event-related games, send ZNS/SMS/surveys, and classify for remarketing after obtaining data.",
        "requirements": [],
        "benefits": [
            "Thưởng",
            "Đào tạo",
            "Khác"
        ],
        "applyUrl": "https://www.vietnamworks.com/nhan-vien-truyen-thong-ky-thuat-so-digital-associate--2040752-jv?source=searchResults&searchType=2&placement=2040802&sortBy=date&qs=0"
    }
];
